// Nivel 4/livros-angular/src/app/LivroLista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../Editora';
import { Livro } from '../Livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Observable, of } from 'rxjs';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(
    servEditora: ControleEditoraService,
    servLivros: ControleLivrosService
  ) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }
  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe((data) => {
      this.editoras = data;
    });

    this.servLivros.obterLivros().subscribe((data) => {
      this.livros = data;
    });
  }

  excluir = (codigo: number): void => {
    this.servLivros.excluirLivro(codigo).subscribe(() => {
      this.servLivros.obterLivros().subscribe((data) => {
        this.livros = data;
      });
    });
  };

  obterNome = (codEditora: number): Observable<string | undefined> => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="d-flex flex-column h-100 w-100 px-5"> <!--não esta funcionando o bootstrap -->
    <h1 class="my-4">Lista de Livros</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th class="bg-dark text-white ">Título</th>
                <th class="bg-dark text-white ">Resumo</th>
                <th class="bg-dark text-white ">Editora</th>
                <th class="bg-dark text-white ">Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>{{ livro.titulo }} <br>
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) | async }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// Nivel 3/livros-react/src/componentes/LivroLista.js
import React, { useState, useEffect, useMemo } from "react";
import Table from "react-bootstrap/Table";
import ControleLivro from "../controle/ControleLivros";
import ControleEditora from "../controle/ControleEditora";
import "bootstrap/dist/css/bootstrap.min.css";
import { arrayLivros } from "../controle/ControleLivros";

function LinhaLivro({ livro, excluir }) {
  const handleDelete = () => {
    excluir(livro.codigo);
  };
  return (
    <tr>
      <td>
        {livro.titulo}
        <br />
        <button className="btn btn-danger" onClick={handleDelete}>
          {" "}
          Excluir{" "}
        </button>
      </td>
      <td className="resumo-coluna">{livro.resumo}</td>
      <td>{livro.nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
}

export function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  const controleLivro = useMemo(() => { return new ControleLivro(arrayLivros); }, []);
  const controleEditora = useMemo(() => { return new ControleEditora(); }, []);

  useEffect(() => {
    if (!carregado) {
      const dadosLivros = controleLivro.obterLivros();
      const livrosComNomeEditora = dadosLivros.map((livro) => {
        const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
        return { ...livro, nomeEditora };
      });

      setLivros(livrosComNomeEditora);
      setCarregado(true);
    }
  }, [carregado, controleLivro, controleEditora]);

  const excluir = (codigo) => {
    controleLivro.excluirLivro(codigo);
    const dadosLivros = controleLivro.obterLivros();
    const livrosComNomeEditora = dadosLivros.map((livro) => {
      const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
      return { ...livro, nomeEditora };
    });
    setLivros(livrosComNomeEditora);
  };

  return (
    <main className="d-flex flex-column h-100 w-100 px-5">
      <h1>Catálogo de Livros</h1>
      {carregado ? (
        <Table striped bordered hover>
          <thead>
            <tr>
              <th className="bg-dark text-white">Título</th>
              <th className="bg-dark text-white">Resumo</th>
              <th className="bg-dark text-white">Editora</th>
              <th className="bg-dark text-white">Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro) => (
              <LinhaLivro key={livro.codigo} livro={livro} excluir={excluir} />
            ))}
          </tbody>
        </Table>
      ) : (
        <p>Carregando...</p>
      )}
    </main>
  );
}
