// Nivel 5/livro-servidor/clientes/livros-next/src/pages/LivroLista.tsx
import React, { useState, useEffect } from "react";
import type { NextPage } from "next";
import styles from "@/styles/Home.module.css";
import { Menu } from "@/classes/componentes/Menu";
import Head from "next/head";
import Table from "react-bootstrap/Table";
import { Livro } from "@/classes/modelo/Livro";
import { LinhaLivro } from "@/classes/componentes/LinhaLivro";
import ControleLivros from "@/classes/controle/ControleLivros";

const LivroLista: NextPage = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState<boolean>(false);
  const controleLivros = new ControleLivros([]);

  useEffect(() => {
    const obterLivros = async () => {
      try {
        const livrosObtidos = await controleLivros.obterLivros();
        setLivros(livrosObtidos);
        setCarregado(true);
      } catch (error) {
        console.error("Erro ao obter livros:", error);
      }
    };

    if (!carregado) {
      obterLivros();
    }
  }, [carregado, controleLivros]);

  const excluirLivro = async (codigo: number) => {
    try {
      await controleLivros.excluirLivro(codigo);
      setCarregado(false);
    } catch (error) {
      console.error("Erro ao excluir livro:", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Loja Next</title>
      </Head>
      <Menu />
      <main className="d-flex flex-column h-100 w-100 px-5">
        <h1>Catálogo de Livros</h1>
        <Table striped bordered hover>
          <thead>
            <tr>
              <th className="bg-dark text-white">Título</th>
              <th className="bg-dark text-white">Resumo</th>
              <th className="bg-dark text-white">Editora</th>
              <th className="bg-dark text-white">Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro
                key={`${index}_${livro.codigo}`}
                livro={livro}
                excluir={excluirLivro}
              />
            ))}
          </tbody>
        </Table>
      </main>
    </div>
  );
};

export default LivroLista;

// Nivel 4/livros-angular/src/app/LivroLista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../Editora';
import { Livro } from '../Livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Observable, of } from 'rxjs';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(
    servEditora: ControleEditoraService,
    servLivros: ControleLivrosService
  ) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }
  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe((editoras) => {
      this.editoras = editoras;
      console.log('Editoras disponíveis:', this.editoras.map(e => e.codEditora));
    });

    this.servLivros.obterLivros().subscribe((livros) => {
      this.livros = livros;
    });
  }

  excluir = (codigo: number): void => {
    this.servLivros.excluirLivro(codigo).subscribe(() => {
      this.servLivros.obterLivros().subscribe((livros) => {
        this.livros = livros;
        console.log('Códigos das editoras nos livros:', this.livros.map(l => l.codEditora));
      });
    });
  };

  obterNome = (codEditora: number): Observable<string | undefined> => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="d-flex flex-column h-100 w-100 px-5">
    <h1 class="my-4">Lista de Livros</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th class="bg-dark text-white ">Título</th>
                <th class="bg-dark text-white ">Resumo</th>
                <th class="bg-dark text-white ">Editora</th>
                <th class="bg-dark text-white ">Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>{{ livro.titulo }} <br>
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>
                <td>{{ livro.resumo }}</td>
                <td>
                    {{ obterNome(livro.codEditora) | async }}
                </td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>
